### ISSUE TITLE
Authentication fails because the token auth does not seem to be supported

### ISSUE THREAD

**Issue by Stegoo** [realestate-com-au/tagfish#15]
Hi,

My `~/.docker/config.json` looks like:

```json
{
	"auths": {
		"https://index.docker.io/v1/": {
			"auth": "c4RlZ278cHh4cnZFNjW1TFaq"
		}
	}
}
```

But when I run: `tagfish update --dry-run config.yml`, I get the following error:

```
ERROR: call to 'https://index.docker.io/v1/repositories/org/repo/tags' failed with 401
```

Looking at the code, it seems that you check for a user and password to login into docker.
Do you have any plans to support the token authentication method?

Thank you

**Comment by mdub** [comment]
We're aware of this short-coming, and hope to address it, shortly.

**Comment by gonzalo-bulnes** [comment]
@mdub Let me know if you need help, I'm happy to jump in : )

**Comment by mdub** [comment]
Update: we've built a successor to Tagfish, [dfresh](https://github.com/realestate-com-au/dfresh), which leverages (parts of) the Docker CLI code, and therefore supports V2 auth tokens, as well as other things like credential-helpers.

**Comment by mdub** [comment]
This will not be fixed, in tagfish.
